"""Task planning data structures.

Defines the data models for task planning and execution.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class TaskStatus(Enum):
    """Status of a task in the execution plan."""

    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


@dataclass
class ToolCall:
    """Represents a single tool call in a task."""

    tool_name: str
    arguments: dict[str, Any]
    call_id: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary format."""
        return {
            "tool_name": self.tool_name,
            "arguments": self.arguments,
            "call_id": self.call_id,
        }


@dataclass
class ToolResult:
    """Result from executing a tool call."""

    call_id: str
    tool_name: str
    success: bool
    result: Any
    error: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary format."""
        return {
            "call_id": self.call_id,
            "tool_name": self.tool_name,
            "success": self.success,
            "result": self.result,
            "error": self.error,
        }


@dataclass
class TaskStep:
    """A single step in the task execution plan."""

    step_id: int
    description: str
    tool_calls: list[ToolCall] = field(default_factory=list)
    status: TaskStatus = TaskStatus.PENDING
    result: Any = None
    error: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary format."""
        return {
            "step_id": self.step_id,
            "description": self.description,
            "tool_calls": [tc.to_dict() for tc in self.tool_calls],
            "status": self.status.value,
            "result": self.result,
            "error": self.error,
        }


@dataclass
class TaskPlan:
    """Complete task execution plan.

    Represents a multi-step plan generated by the LLM to accomplish
    a user's request.
    """

    goal: str
    steps: list[TaskStep] = field(default_factory=list)
    current_step: int = 0
    status: TaskStatus = TaskStatus.PENDING
    final_result: Any = None

    def add_step(self, description: str, tool_calls: list[ToolCall] | None = None) -> TaskStep:
        """Add a new step to the plan.

        Args:
            description: Human-readable description of the step
            tool_calls: Optional list of tool calls for this step

        Returns:
            The created TaskStep
        """
        step = TaskStep(
            step_id=len(self.steps),
            description=description,
            tool_calls=tool_calls or [],
        )
        self.steps.append(step)
        return step

    def get_current_step(self) -> TaskStep | None:
        """Get the current step being executed.

        Returns:
            Current TaskStep or None if plan is complete
        """
        if self.current_step < len(self.steps):
            return self.steps[self.current_step]
        return None

    def advance_step(self) -> bool:
        """Move to the next step.

        Returns:
            True if advanced, False if already at end
        """
        if self.current_step < len(self.steps) - 1:
            self.current_step += 1
            return True
        return False

    def is_complete(self) -> bool:
        """Check if all steps are complete.

        Returns:
            True if plan execution is finished
        """
        return self.current_step >= len(self.steps) or self.status in [
            TaskStatus.COMPLETED,
            TaskStatus.FAILED,
        ]

    def mark_complete(self, result: Any = None) -> None:
        """Mark the plan as successfully completed.

        Args:
            result: Final result of the plan execution
        """
        self.status = TaskStatus.COMPLETED
        self.final_result = result

    def mark_failed(self, error: str) -> None:
        """Mark the plan as failed.

        Args:
            error: Error message describing the failure
        """
        self.status = TaskStatus.FAILED
        self.final_result = {"error": error}

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary format.

        Returns:
            Dictionary representation of the plan
        """
        return {
            "goal": self.goal,
            "steps": [step.to_dict() for step in self.steps],
            "current_step": self.current_step,
            "status": self.status.value,
            "final_result": self.final_result,
        }


__all__ = [
    "TaskStatus",
    "ToolCall",
    "ToolResult",
    "TaskStep",
    "TaskPlan",
]
